/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Kanata Scraper API
 * API documentation for Kanata Scraper (Otakudesu, etc.)
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from './instance';
export type GetApiServerinfo200Memory = { [key: string]: unknown };

export type GetApiServerinfo200Cpu = { [key: string]: unknown };

export type GetApiServerinfo200 = {
  platform?: string;
  uptime?: string;
  memory?: GetApiServerinfo200Memory;
  cpu?: GetApiServerinfo200Cpu;
};

export type GetApiScraperTiktokParams = {
/**
 * TikTok video URL
 */
url: string;
};

export type GetApiScraperTiktok200Stats = { [key: string]: unknown };

export type GetApiScraperTiktok200 = {
  title?: string;
  author?: string;
  cover?: string;
  nowm?: string;
  music?: string;
  stats?: GetApiScraperTiktok200Stats;
};

export type GetApiNeonimeHome200OngoingItem = { [key: string]: unknown };

export type GetApiNeonimeHome200CompleteItem = { [key: string]: unknown };

export type GetApiNeonimeHome200 = {
  ongoing?: GetApiNeonimeHome200OngoingItem[];
  complete?: GetApiNeonimeHome200CompleteItem[];
};

export type GetApiNeonimeSearchParams = {
q: string;
};

export type GetApiNeonimeSearch200Item = { [key: string]: unknown };

export type GetApiNeonimeAnimeSlug200 = { [key: string]: unknown };

export type GetApiScraperSholatCities200Item = {
  id?: string;
  lokasi?: string;
};

export type GetApiScraperSholatCityId200 = { [key: string]: unknown };

export type GetApiScraperTest200 = {
  title?: string;
  message?: string;
};

export type GetApiOtakudesuHome200OngoingItem = {
  title?: string;
  episode?: string;
  day?: string;
  date?: string;
  thumb?: string;
  slug?: string;
};

export type GetApiOtakudesuHome200CompleteItem = {
  title?: string;
  episode?: string;
  score?: string;
  date?: string;
  thumb?: string;
  slug?: string;
};

export type GetApiOtakudesuHome200 = {
  ongoing?: GetApiOtakudesuHome200OngoingItem[];
  complete?: GetApiOtakudesuHome200CompleteItem[];
};

export type GetApiOtakudesuSchedule200ItemAnimeListItem = {
  title?: string;
  slug?: string;
};

export type GetApiOtakudesuSchedule200Item = {
  day?: string;
  animeList?: GetApiOtakudesuSchedule200ItemAnimeListItem[];
};

export type GetApiOtakudesuCompleteParams = {
/**
 * Page number (default is 1)
 */
page?: string;
};

export type GetApiOtakudesuComplete200Item = {
  title?: string;
  episode?: string;
  score?: string;
  date?: string;
  thumb?: string;
  slug?: string;
};

export type GetApiOtakudesuOngoingParams = {
/**
 * Page number (default is 1)
 */
page?: string;
};

export type GetApiOtakudesuOngoing200Item = {
  title?: string;
  episode?: string;
  day?: string;
  date?: string;
  thumb?: string;
  slug?: string;
};

export type GetApiOtakudesuSearchParams = {
/**
 * Search query (e.g., one piece)
 */
q: string;
};

export type GetApiOtakudesuSearch200Item = {
  title?: string;
  thumb?: string;
  genres?: string[];
  status?: string;
  rating?: string;
  slug?: string;
};

/**
 * @nullable
 */
export type GetApiOtakudesuAnimeSlug200BatchLink = {
  title?: string;
  slug?: string;
} | null;

export type GetApiOtakudesuAnimeSlug200EpisodeListItem = {
  title?: string;
  slug?: string;
  date?: string;
};

export type GetApiOtakudesuAnimeSlug200 = {
  title?: string;
  japanese?: string;
  score?: string;
  producer?: string;
  type?: string;
  status?: string;
  total_episode?: string;
  duration?: string;
  release_date?: string;
  studio?: string;
  genres?: string[];
  thumb?: string;
  synopsis?: string;
  /** @nullable */
  batch_link?: GetApiOtakudesuAnimeSlug200BatchLink;
  episode_list?: GetApiOtakudesuAnimeSlug200EpisodeListItem[];
};

export type GetApiOtakudesuBatchSlug200DownloadListItemLinksItemLinksItem = {
  name?: string;
  url?: string;
};

export type GetApiOtakudesuBatchSlug200DownloadListItemLinksItem = {
  quality?: string;
  size?: string;
  links?: GetApiOtakudesuBatchSlug200DownloadListItemLinksItemLinksItem[];
};

export type GetApiOtakudesuBatchSlug200DownloadListItem = {
  title?: string;
  links?: GetApiOtakudesuBatchSlug200DownloadListItemLinksItem[];
};

export type GetApiOtakudesuBatchSlug200 = {
  title?: string;
  thumb?: string;
  download_list?: GetApiOtakudesuBatchSlug200DownloadListItem[];
};

export type GetApiOtakudesuGenres200Item = {
  name?: string;
  slug?: string;
};

export type GetApiOtakudesuGenresSlugParams = {
/**
 * Page number (default is 1)
 */
page?: string;
};

export type GetApiOtakudesuGenresSlug200Item = {
  title?: string;
  studio?: string;
  eps?: string;
  rating?: string;
  thumb?: string;
  slug?: string;
  date?: string;
  genres?: string[];
};

export type GetApiOtakudesuAnimeList200ItemListItem = {
  title?: string;
  slug?: string;
};

export type GetApiOtakudesuAnimeList200Item = {
  letter?: string;
  list?: GetApiOtakudesuAnimeList200ItemListItem[];
};

/**
 * JSON payload needed for /stream endpoint
 */
export type GetApiOtakudesuEpisodeSlug200MirrorsItemPayload = { [key: string]: unknown };

export type GetApiOtakudesuEpisodeSlug200MirrorsItem = {
  name?: string;
  /** JSON payload needed for /stream endpoint */
  payload?: GetApiOtakudesuEpisodeSlug200MirrorsItemPayload;
};

export type GetApiOtakudesuEpisodeSlug200 = {
  title?: string;
  /** URL of the default iframe stream */
  defaultStream?: string;
  mirrors?: GetApiOtakudesuEpisodeSlug200MirrorsItem[];
};

/**
 * The payload object obtained from the /episode/{slug} endpoint
 */
export type PostApiOtakudesuStreamBodyPayload = { [key: string]: unknown };

export type PostApiOtakudesuStreamBody = {
  /** The payload object obtained from the /episode/{slug} endpoint */
  payload: PostApiOtakudesuStreamBodyPayload;
};

export type PostApiOtakudesuStream200 = {
  /** The resolved iframe URL */
  iframe?: string;
  /** The raw HTML containing the iframe (decoded) */
  html?: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getKanataScraperAPI = () => {
/**
 * Returns system statistics (CPU, Memory, Uptime).
 * @summary Get Server Info
 */
const getApiServerinfo = (
    
 options?: SecondParameter<typeof customInstance<GetApiServerinfo200>>,) => {
      return customInstance<GetApiServerinfo200>(
      {url: `/api/serverinfo`, method: 'GET'
    },
      options);
    }
  
/**
 * Downloads TikTok video without watermark.
 * @summary TikTok Downloader
 */
const getApiScraperTiktok = (
    params: GetApiScraperTiktokParams,
 options?: SecondParameter<typeof customInstance<GetApiScraperTiktok200>>,) => {
      return customInstance<GetApiScraperTiktok200>(
      {url: `/api/scraper/tiktok`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * Scrapes the latest ongoing and complete anime from Neonime.
 * @summary Get Neonime Homepage Data
 */
const getApiNeonimeHome = (
    
 options?: SecondParameter<typeof customInstance<GetApiNeonimeHome200>>,) => {
      return customInstance<GetApiNeonimeHome200>(
      {url: `/api/neonime/home`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Search Anime on Neonime
 */
const getApiNeonimeSearch = (
    params: GetApiNeonimeSearchParams,
 options?: SecondParameter<typeof customInstance<GetApiNeonimeSearch200Item[]>>,) => {
      return customInstance<GetApiNeonimeSearch200Item[]>(
      {url: `/api/neonime/search`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * @summary Get Neonime Anime Details
 */
const getApiNeonimeAnimeSlug = (
    slug: string,
 options?: SecondParameter<typeof customInstance<GetApiNeonimeAnimeSlug200>>,) => {
      return customInstance<GetApiNeonimeAnimeSlug200>(
      {url: `/api/neonime/anime/${slug}`, method: 'GET'
    },
      options);
    }
  
/**
 * Returns a list of all supported cities for prayer schedules.
 * @summary Get Sholat Cities
 */
const getApiScraperSholatCities = (
    
 options?: SecondParameter<typeof customInstance<GetApiScraperSholatCities200Item[]>>,) => {
      return customInstance<GetApiScraperSholatCities200Item[]>(
      {url: `/api/scraper/sholat/cities`, method: 'GET'
    },
      options);
    }
  
/**
 * Returns daily prayer schedule for a specific city ID.
 * @summary Get Prayer Schedule
 */
const getApiScraperSholatCityId = (
    cityId: string,
 options?: SecondParameter<typeof customInstance<GetApiScraperSholatCityId200>>,) => {
      return customInstance<GetApiScraperSholatCityId200>(
      {url: `/api/scraper/sholat/${cityId}`, method: 'GET'
    },
      options);
    }
  
/**
 * Scrapes example.com to verify scraping capabilities.
 * @summary Test Scraper
 */
const getApiScraperTest = (
    
 options?: SecondParameter<typeof customInstance<GetApiScraperTest200>>,) => {
      return customInstance<GetApiScraperTest200>(
      {url: `/api/scraper/test`, method: 'GET'
    },
      options);
    }
  
/**
 * Scrapes the latest ongoing and complete anime from the Otakudesu homepage.
 * @summary Get Otakudesu Homepage Data
 */
const getApiOtakudesuHome = (
    
 options?: SecondParameter<typeof customInstance<GetApiOtakudesuHome200>>,) => {
      return customInstance<GetApiOtakudesuHome200>(
      {url: `/api/otakudesu/home`, method: 'GET'
    },
      options);
    }
  
/**
 * Scrapes the weekly release schedule from Otakudesu.
 * @summary Get Otakudesu Release Schedule
 */
const getApiOtakudesuSchedule = (
    
 options?: SecondParameter<typeof customInstance<GetApiOtakudesuSchedule200Item[]>>,) => {
      return customInstance<GetApiOtakudesuSchedule200Item[]>(
      {url: `/api/otakudesu/schedule`, method: 'GET'
    },
      options);
    }
  
/**
 * Scrapes the list of completed anime from Otakudesu with pagination.
 * @summary Get Otakudesu Complete Anime List
 */
const getApiOtakudesuComplete = (
    params?: GetApiOtakudesuCompleteParams,
 options?: SecondParameter<typeof customInstance<GetApiOtakudesuComplete200Item[]>>,) => {
      return customInstance<GetApiOtakudesuComplete200Item[]>(
      {url: `/api/otakudesu/complete`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * Scrapes the list of ongoing anime from Otakudesu with pagination.
 * @summary Get Otakudesu Ongoing Anime List
 */
const getApiOtakudesuOngoing = (
    params?: GetApiOtakudesuOngoingParams,
 options?: SecondParameter<typeof customInstance<GetApiOtakudesuOngoing200Item[]>>,) => {
      return customInstance<GetApiOtakudesuOngoing200Item[]>(
      {url: `/api/otakudesu/ongoing`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * Searches for anime on Otakudesu using a query string.
 * @summary Search Anime
 */
const getApiOtakudesuSearch = (
    params: GetApiOtakudesuSearchParams,
 options?: SecondParameter<typeof customInstance<GetApiOtakudesuSearch200Item[]>>,) => {
      return customInstance<GetApiOtakudesuSearch200Item[]>(
      {url: `/api/otakudesu/search`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * Scrapes details of a specific anime and its episode list.
 * @summary Get Anime Details
 */
const getApiOtakudesuAnimeSlug = (
    slug: string,
 options?: SecondParameter<typeof customInstance<GetApiOtakudesuAnimeSlug200>>,) => {
      return customInstance<GetApiOtakudesuAnimeSlug200>(
      {url: `/api/otakudesu/anime/${slug}`, method: 'GET'
    },
      options);
    }
  
/**
 * Scrapes batch download links for a specific anime batch.
 * @summary Get Batch Download Links
 */
const getApiOtakudesuBatchSlug = (
    slug: string,
 options?: SecondParameter<typeof customInstance<GetApiOtakudesuBatchSlug200>>,) => {
      return customInstance<GetApiOtakudesuBatchSlug200>(
      {url: `/api/otakudesu/batch/${slug}`, method: 'GET'
    },
      options);
    }
  
/**
 * Scrapes the list of available genres from Otakudesu.
 * @summary Get Otakudesu Genre List
 */
const getApiOtakudesuGenres = (
    
 options?: SecondParameter<typeof customInstance<GetApiOtakudesuGenres200Item[]>>,) => {
      return customInstance<GetApiOtakudesuGenres200Item[]>(
      {url: `/api/otakudesu/genres`, method: 'GET'
    },
      options);
    }
  
/**
 * Scrapes the list of anime for a specific genre with pagination.
 * @summary Get Anime by Genre
 */
const getApiOtakudesuGenresSlug = (
    slug: string,
    params?: GetApiOtakudesuGenresSlugParams,
 options?: SecondParameter<typeof customInstance<GetApiOtakudesuGenresSlug200Item[]>>,) => {
      return customInstance<GetApiOtakudesuGenresSlug200Item[]>(
      {url: `/api/otakudesu/genres/${slug}`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * Scrapes all anime titles from Otakudesu grouped by their starting letter.
 * @summary Get All Anime List
 */
const getApiOtakudesuAnimeList = (
    
 options?: SecondParameter<typeof customInstance<GetApiOtakudesuAnimeList200Item[]>>,) => {
      return customInstance<GetApiOtakudesuAnimeList200Item[]>(
      {url: `/api/otakudesu/anime-list`, method: 'GET'
    },
      options);
    }
  
/**
 * Scrapes an episode page to get the title, default stream, and mirror list.
 * @summary Get Episode Details
 */
const getApiOtakudesuEpisodeSlug = (
    slug: string,
 options?: SecondParameter<typeof customInstance<GetApiOtakudesuEpisodeSlug200>>,) => {
      return customInstance<GetApiOtakudesuEpisodeSlug200>(
      {url: `/api/otakudesu/episode/${slug}`, method: 'GET'
    },
      options);
    }
  
/**
 * Resolves the actual iframe URL for a specific mirror using the payload from the episode details.
 * @summary Resolve Stream URL
 */
const postApiOtakudesuStream = (
    postApiOtakudesuStreamBody: PostApiOtakudesuStreamBody,
 options?: SecondParameter<typeof customInstance<PostApiOtakudesuStream200>>,) => {
      return customInstance<PostApiOtakudesuStream200>(
      {url: `/api/otakudesu/stream`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiOtakudesuStreamBody
    },
      options);
    }
  
return {getApiServerinfo,getApiScraperTiktok,getApiNeonimeHome,getApiNeonimeSearch,getApiNeonimeAnimeSlug,getApiScraperSholatCities,getApiScraperSholatCityId,getApiScraperTest,getApiOtakudesuHome,getApiOtakudesuSchedule,getApiOtakudesuComplete,getApiOtakudesuOngoing,getApiOtakudesuSearch,getApiOtakudesuAnimeSlug,getApiOtakudesuBatchSlug,getApiOtakudesuGenres,getApiOtakudesuGenresSlug,getApiOtakudesuAnimeList,getApiOtakudesuEpisodeSlug,postApiOtakudesuStream}};
export type GetApiServerinfoResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKanataScraperAPI>['getApiServerinfo']>>>
export type GetApiScraperTiktokResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKanataScraperAPI>['getApiScraperTiktok']>>>
export type GetApiNeonimeHomeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKanataScraperAPI>['getApiNeonimeHome']>>>
export type GetApiNeonimeSearchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKanataScraperAPI>['getApiNeonimeSearch']>>>
export type GetApiNeonimeAnimeSlugResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKanataScraperAPI>['getApiNeonimeAnimeSlug']>>>
export type GetApiScraperSholatCitiesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKanataScraperAPI>['getApiScraperSholatCities']>>>
export type GetApiScraperSholatCityIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKanataScraperAPI>['getApiScraperSholatCityId']>>>
export type GetApiScraperTestResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKanataScraperAPI>['getApiScraperTest']>>>
export type GetApiOtakudesuHomeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKanataScraperAPI>['getApiOtakudesuHome']>>>
export type GetApiOtakudesuScheduleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKanataScraperAPI>['getApiOtakudesuSchedule']>>>
export type GetApiOtakudesuCompleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKanataScraperAPI>['getApiOtakudesuComplete']>>>
export type GetApiOtakudesuOngoingResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKanataScraperAPI>['getApiOtakudesuOngoing']>>>
export type GetApiOtakudesuSearchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKanataScraperAPI>['getApiOtakudesuSearch']>>>
export type GetApiOtakudesuAnimeSlugResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKanataScraperAPI>['getApiOtakudesuAnimeSlug']>>>
export type GetApiOtakudesuBatchSlugResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKanataScraperAPI>['getApiOtakudesuBatchSlug']>>>
export type GetApiOtakudesuGenresResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKanataScraperAPI>['getApiOtakudesuGenres']>>>
export type GetApiOtakudesuGenresSlugResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKanataScraperAPI>['getApiOtakudesuGenresSlug']>>>
export type GetApiOtakudesuAnimeListResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKanataScraperAPI>['getApiOtakudesuAnimeList']>>>
export type GetApiOtakudesuEpisodeSlugResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKanataScraperAPI>['getApiOtakudesuEpisodeSlug']>>>
export type PostApiOtakudesuStreamResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKanataScraperAPI>['postApiOtakudesuStream']>>>
